"use client";

// Riso Kit gradient — generated by Riso Kit (https://risokit.dev)
// Drop into any React 18+ project. No dependencies. Fills its parent.

import {useEffect, useRef} from "react";

const STOP_POS: [number, number][] = [[0.05, 0.05], [0.95, 0.1], [0, 0.95], [0.5, 1], [1, 1]];
const STOP_COLOR: [number, number, number][] = [[0.45, 0.35, 0.95], [0.98, 0.35, 0.5], [1, 0.92, 0.25], [0.2, 0.85, 0.95], [0.98, 0.5, 0.3]];
const STOP_WEIGHT: number[] = [1, 1, 1, 1, 1];
const CELL = 10;
const DOT_SCALE = 2.2;
const NOISE = 0.03;
const SHAPE: 0 | 1 | 2 | 3 | 4 = 0;

const VERT = `#version 300 es
in vec2 a_pos;
void main() { gl_Position = vec4(a_pos, 0.0, 1.0); }
`;

const FRAG = `#version 300 es
precision highp float;
out vec4 outColor;
uniform vec2 u_resolution;
uniform float u_cell;
uniform float u_dotScale;
uniform float u_noise;
uniform int u_shape;
uniform int u_stopCount;
uniform vec2 u_stopPos[5];
uniform vec3 u_stopColor[5];
uniform float u_stopWeight[5];

float hash(vec2 p) {
  p = fract(p * vec2(123.34, 456.21));
  p += dot(p, p + 45.32);
  return fract(p.x * p.y);
}

vec3 sampleGradient(vec2 uv) {
  vec3 acc = vec3(0.0);
  float wsum = 0.0;
  for (int i = 0; i < 5; i++) {
    if (i >= u_stopCount) break;
    float d = distance(uv, u_stopPos[i]);
    float w = u_stopWeight[i] / (d * d + 0.001);
    acc += u_stopColor[i] * w;
    wsum += w;
  }
  return acc / max(wsum, 0.0001);
}

float shapeMask(vec2 cellUV, float radius) {
  if (u_shape == 0) {
    return 1.0 - smoothstep(radius - 0.02, radius + 0.02, length(cellUV));
  } else if (u_shape == 1) {
    float r = radius * 0.9;
    vec2 a = abs(cellUV);
    return 1.0 - smoothstep(r - 0.02, r + 0.02, max(a.x, a.y));
  } else if (u_shape == 2) {
    return 1.0 - smoothstep(radius - 0.02, radius + 0.02, abs(cellUV.y));
  } else {
    vec2 a = abs(cellUV);
    float d = max(a.x * 0.866 + a.y * 0.5, a.y);
    return 1.0 - smoothstep(radius - 0.02, radius + 0.02, d);
  }
}

void main() {
  vec2 frag = gl_FragCoord.xy;
  vec2 uv = frag / u_resolution;
  vec3 col = vec3(1.0);
  if (u_shape == 4) {
    // Riso paper texture mode — continuous gradient + multi-scale grain.
    col = sampleGradient(uv);
    float fiber   = (hash(frag * 1.4) - 0.5) * 0.03;
    float cluster = (hash(floor(frag / 4.0)) - 0.5) * 0.02;
    float wash    = (hash(floor(frag / 18.0)) - 0.5) * 0.012;
    col += fiber + cluster + wash;
  } else {
    vec2 cellId = floor(frag / u_cell);
    vec2 cellCenter = (cellId + 0.5) * u_cell;
    vec2 cellUV = (frag - cellCenter) / u_cell;
    vec3 cellColor = sampleGradient(cellCenter / u_resolution);
    float lum = dot(cellColor, vec3(0.299, 0.587, 0.114));
    float radius = (1.0 - lum) * 0.5 * u_dotScale;
    float mask = shapeMask(cellUV, radius);
    col = mix(vec3(1.0), cellColor, mask);
  }
  col += (hash(frag) - 0.5) * u_noise;
  outColor = vec4(col, 1.0);
}
`;

function compile(gl: WebGL2RenderingContext, type: number, src: string) {
  const sh = gl.createShader(type)!;
  gl.shaderSource(sh, src);
  gl.compileShader(sh);
  if (!gl.getShaderParameter(sh, gl.COMPILE_STATUS)) {
    throw new Error(gl.getShaderInfoLog(sh) ?? "shader compile failed");
  }
  return sh;
}

export function RisoKitBackground() {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const gl = canvas.getContext("webgl2");
    if (!gl) {
      console.error("WebGL2 not supported");
      return;
    }
    const vs = compile(gl, gl.VERTEX_SHADER, VERT);
    const fs = compile(gl, gl.FRAGMENT_SHADER, FRAG);
    const program = gl.createProgram()!;
    gl.attachShader(program, vs);
    gl.attachShader(program, fs);
    gl.linkProgram(program);

    const buf = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, buf);
    gl.bufferData(
      gl.ARRAY_BUFFER,
      new Float32Array([-1, -1, 1, -1, -1, 1, -1, 1, 1, -1, 1, 1]),
      gl.STATIC_DRAW
    );
    const loc = gl.getAttribLocation(program, "a_pos");
    gl.enableVertexAttribArray(loc);
    gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0);

    const u = (n: string) => gl.getUniformLocation(program, n);
    const positions = new Float32Array(STOP_POS.flat());
    const colors = new Float32Array(STOP_COLOR.flat());
    const weights = new Float32Array(STOP_WEIGHT);

    const draw = () => {
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      const w = Math.floor(canvas.clientWidth * dpr);
      const h = Math.floor(canvas.clientHeight * dpr);
      if (canvas.width !== w || canvas.height !== h) {
        canvas.width = w;
        canvas.height = h;
      }
      gl.viewport(0, 0, canvas.width, canvas.height);
      gl.useProgram(program);
      gl.uniform2f(u("u_resolution")!, canvas.width, canvas.height);
      gl.uniform1f(u("u_cell")!, CELL * dpr);
      gl.uniform1f(u("u_dotScale")!, DOT_SCALE);
      gl.uniform1f(u("u_noise")!, NOISE);
      gl.uniform1i(u("u_shape")!, SHAPE);
      gl.uniform1i(u("u_stopCount")!, STOP_POS.length);
      gl.uniform2fv(u("u_stopPos[0]")!, positions);
      gl.uniform3fv(u("u_stopColor[0]")!, colors);
      gl.uniform1fv(u("u_stopWeight[0]")!, weights);
      gl.drawArrays(gl.TRIANGLES, 0, 6);
    };

    draw();
    const ro = new ResizeObserver(draw);
    ro.observe(canvas);
    return () => {
      ro.disconnect();
      gl.deleteProgram(program);
      gl.deleteShader(vs);
      gl.deleteShader(fs);
    };
  }, []);

  return (
    <canvas
      ref={canvasRef}
      style={{ width: "100%", height: "100%", display: "block", background: "white" }}
    />
  );
}
